imagedb/app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from app.config import configs

db = SQLAlchemy()

def create_app(app_config='development'):

  app = Flask(__name__)
  app.config.from_object(configs[app_config])

  db.init_app(app)

  from app.main.routes import main
  
  app.register_blueprint(main)

  return app

imagedb/app/main/routes.py
from flask import Blueprint, render_template, redirect, url_for, request
from app.main.form import TaskForm
from app import db
from app.model import Task

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/', methods=['GET'])
def index():
  list_of_todos = Task.query.order_by(Task.id).all()
  return render_template('index.html', list_of_todos=list_of_todos)

@main.route('/new', methods=['GET'])
def new():
  form = TaskForm()
  return render_template('new.html', form=form)

@main.route('/show/<int:id>', methods=['GET'])
def show(id):
  todo = Task.query.filter_by(id=id).first()
  return render_template('show.html', todo=todo)

@main.route('/create', methods=['POST'])
def create():
  form = TaskForm()
  if request.method == 'POST' and form.validate_on_submit():
    todo = Task(todo=form.name.data)
    db.session.add(todo)
    db.session.commit()
  return redirect(url_for('main.index'))

imagedb/app/templates/index.html
{% extends 'layout.html' %}

{% block content %}
  <div>
    <a href={{ url_for('main.new') }}>Create a new todo</a>
    {% for items in list_of_todos %}
      <ul>
        <li><a href= {{ url_for('main.show', id=items.id ) }}>{{ items.todo }}</a></li>
      </ul>
    {% endfor %}
  </div>
{% endblock %}

imagedb/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>

imagedb/app/templates/new.html
{% extends 'layout.html' %}

{% block content %}
  <div>
    <form action="/create" method="POST">
      {{ form.csrf_token }}
      {{ form.name.label }} {{ form.name }}
      {{ form.submit }}
    </form>
    <a href={{ url_for('main.index') }}>index</a>
  </div>
{% endblock %}

imagedb/app/templates/show.html
{% extends 'layout.html' %}

{% block content %}
  <div>
    {{ todo.todo }}
  </div>
{% endblock %}